--------------------------------------------------------
--  File created - Monday-December-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CREDENTIALS_MANAGER
--------------------------------------------------------

  CREATE TABLE "CREDENTIAL_MANAGER"."CREDENTIALS_MANAGER" 
   (	"ACCOUNT_ID" VARCHAR2(25 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"PASSWORD_TYPE" VARCHAR2(15 BYTE), 
	"ACCOUNT_URL" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence CREDENTIAL_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CREDENTIAL_MANAGER"."CREDENTIAL_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE ;
REM INSERTING into CREDENTIAL_MANAGER.CREDENTIALS_MANAGER
SET DEFINE OFF;
Insert into CREDENTIAL_MANAGER.CREDENTIALS_MANAGER (ACCOUNT_ID,ACCOUNT_NAME,USER_ID,PASSWORD,PASSWORD_TYPE,ACCOUNT_URL) values ('16','Bank of america','rishi2616','Eyeofdtiger#16','login','https://www.bankofamerica.com');
Insert into CREDENTIAL_MANAGER.CREDENTIALS_MANAGER (ACCOUNT_ID,ACCOUNT_NAME,USER_ID,PASSWORD,PASSWORD_TYPE,ACCOUNT_URL) values ('13','SBI','rishi2616','Eyeofdtiger#16','Login','http://www.onlinesbi.com');
Insert into CREDENTIAL_MANAGER.CREDENTIALS_MANAGER (ACCOUNT_ID,ACCOUNT_NAME,USER_ID,PASSWORD,PASSWORD_TYPE,ACCOUNT_URL) values ('17','Chase Credit Card','rishi2616','Eyeofdtiger#16','login','https://www.chase.com');
--------------------------------------------------------
--  Constraints for Table CREDENTIALS_MANAGER
--------------------------------------------------------

  ALTER TABLE "CREDENTIAL_MANAGER"."CREDENTIALS_MANAGER" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CREDENTIAL_MANAGER"."CREDENTIALS_MANAGER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CREDENTIAL_MANAGER"."CREDENTIALS_MANAGER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "CREDENTIAL_MANAGER"."CREDENTIALS_MANAGER" ADD PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
