CREATE USER JPA_TRAINING
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for JPA_TRAINING 
  GRANT CONNECT TO JPA_TRAINING;
  GRANT DBA TO JPA_TRAINING;
  GRANT RESOURCE TO JPA_TRAINING;
  ALTER USER JPA_TRAINING DEFAULT ROLE ALL;
  -- 1 System Privilege for JPA_TRAINING 
  GRANT UNLIMITED TABLESPACE TO JPA_TRAINING;


