CREATE USER SERVLET_TRAINING
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  PASSWORD EXPIRE
  ACCOUNT UNLOCK;
  -- 1 Role for SERVLET_TRAINING 
  GRANT DBA TO SERVLET_TRAINING;
  ALTER USER SERVLET_TRAINING DEFAULT ROLE ALL;
  -- 1 System Privilege for SERVLET_TRAINING 
  GRANT UNLIMITED TABLESPACE TO SERVLET_TRAINING;


