CREATE USER SPRING_HIBERNATE_MVC
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for SPRING_HIBERNATE_MVC 
  GRANT DBA TO SPRING_HIBERNATE_MVC;
  ALTER USER SPRING_HIBERNATE_MVC DEFAULT ROLE ALL;
  -- 1 System Privilege for SPRING_HIBERNATE_MVC 
  GRANT UNLIMITED TABLESPACE TO SPRING_HIBERNATE_MVC;


