CREATE USER SPRING_HIBERNATE
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for SPRING_HIBERNATE 
  GRANT DBA TO SPRING_HIBERNATE;
  ALTER USER SPRING_HIBERNATE DEFAULT ROLE ALL;
  -- 1 System Privilege for SPRING_HIBERNATE 
  GRANT UNLIMITED TABLESPACE TO SPRING_HIBERNATE;


