--------------------------------------------------------
--  File created - Monday-December-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISCIPLINE
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."DISCIPLINE" 
   (	"DISCIPLINE_ID" NUMBER(10,0), 
	"DISCIPLINE_NAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENGCOURSE
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."ENGCOURSE" 
   (	"ID" NUMBER(10,0), 
	"COURSE_NAME" VARCHAR2(255 CHAR), 
	"COURSE_PRICE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENGSTUDENT
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."ENGSTUDENT" 
   (	"ID" NUMBER(10,0), 
	"ADMISSSION_YEAR" NUMBER(10,0), 
	"MAJOR" VARCHAR2(255 CHAR), 
	"STUDENT_NAME" VARCHAR2(255 CHAR), 
	"DISCIPLINE_DISCIPLINE_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENG_STUDENT_COURSE
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."ENG_STUDENT_COURSE" 
   (	"STUDENT_ID" NUMBER(10,0), 
	"COURSE_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXAM_RESULTS
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."EXAM_RESULTS" 
   (	"EXAM_ID" NUMBER(10,0), 
	"EXAM_YEAR" VARCHAR2(255 CHAR), 
	"DISCIPLINE_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HT_ADMIN_USER
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SPRING_HIBERNATE"."HT_ADMIN_USER" 
   (	"REGISTRATION_ID" VARCHAR2(255 CHAR)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table HT_REGISTRATIONINFO
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SPRING_HIBERNATE"."HT_REGISTRATIONINFO" 
   (	"REGISTRATION_ID" VARCHAR2(255 CHAR)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table HT_STUDENT
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SPRING_HIBERNATE"."HT_STUDENT" 
   (	"REGISTRATION_ID" VARCHAR2(255 CHAR)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table REGISTRATIONINFO
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."REGISTRATIONINFO" 
   (	"ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"USER_TYPE" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTEXAMRESULT
--------------------------------------------------------

  CREATE TABLE "SPRING_HIBERNATE"."STUDENTEXAMRESULT" 
   (	"RESULTID" NUMBER(10,0), 
	"PERCENTILE" VARCHAR2(255 CHAR), 
	"EXAM_ID" NUMBER(10,0), 
	"THESTUDENT_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING_HIBERNATE"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into SPRING_HIBERNATE.DISCIPLINE
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.ENGCOURSE
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.ENGSTUDENT
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.ENG_STUDENT_COURSE
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.EXAM_RESULTS
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.HT_ADMIN_USER
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.HT_REGISTRATIONINFO
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.HT_STUDENT
SET DEFINE OFF;
REM INSERTING into SPRING_HIBERNATE.REGISTRATIONINFO
SET DEFINE OFF;
Insert into SPRING_HIBERNATE.REGISTRATIONINFO (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USER_ID,USER_TYPE) values (25,'sly.mania42@gmail.com','Kingshuk','Mukherjee','password','rishi2616','A');
Insert into SPRING_HIBERNATE.REGISTRATIONINFO (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USER_ID,USER_TYPE) values (26,'deeksha.jiya@gmail.com','Deeksha','Banerjee','password','deekshab','S');
Insert into SPRING_HIBERNATE.REGISTRATIONINFO (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,USER_ID,USER_TYPE) values (44,'scorpion_kingshuk@yahoo.co.in','Kingshuk','Mukherjee','password','rishi1626','S');
REM INSERTING into SPRING_HIBERNATE.STUDENTEXAMRESULT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UK_7LVU1J72YLAD6WSWJ4Q1QAP2M
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING_HIBERNATE"."UK_7LVU1J72YLAD6WSWJ4Q1QAP2M" ON "SPRING_HIBERNATE"."EXAM_RESULTS" ("DISCIPLINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HT_STUDENT
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."HT_STUDENT" MODIFY ("REGISTRATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENG_STUDENT_COURSE
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."ENG_STUDENT_COURSE" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."ENG_STUDENT_COURSE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTEXAMRESULT
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."STUDENTEXAMRESULT" MODIFY ("RESULTID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."STUDENTEXAMRESULT" ADD PRIMARY KEY ("RESULTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENGSTUDENT
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."ENGSTUDENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."ENGSTUDENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTRATIONINFO
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."REGISTRATIONINFO" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."REGISTRATIONINFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAM_RESULTS
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."EXAM_RESULTS" MODIFY ("EXAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."EXAM_RESULTS" ADD PRIMARY KEY ("EXAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SPRING_HIBERNATE"."EXAM_RESULTS" ADD CONSTRAINT "UK_7LVU1J72YLAD6WSWJ4Q1QAP2M" UNIQUE ("DISCIPLINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HT_ADMIN_USER
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."HT_ADMIN_USER" MODIFY ("REGISTRATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISCIPLINE
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."DISCIPLINE" MODIFY ("DISCIPLINE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."DISCIPLINE" ADD PRIMARY KEY ("DISCIPLINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENGCOURSE
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."ENGCOURSE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPRING_HIBERNATE"."ENGCOURSE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HT_REGISTRATIONINFO
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."HT_REGISTRATIONINFO" MODIFY ("REGISTRATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENGSTUDENT
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."ENGSTUDENT" ADD CONSTRAINT "FK965YNRCMOOESS13E7WW8D4XLU" FOREIGN KEY ("DISCIPLINE_DISCIPLINE_ID")
	  REFERENCES "SPRING_HIBERNATE"."DISCIPLINE" ("DISCIPLINE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENG_STUDENT_COURSE
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."ENG_STUDENT_COURSE" ADD CONSTRAINT "FKI2W48D9ANF7LU6YG3SQY0HXYS" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "SPRING_HIBERNATE"."ENGCOURSE" ("ID") ENABLE;
 
  ALTER TABLE "SPRING_HIBERNATE"."ENG_STUDENT_COURSE" ADD CONSTRAINT "FKR0U54VBIV6S76KA9E2MUOTMNX" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SPRING_HIBERNATE"."ENGSTUDENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAM_RESULTS
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."EXAM_RESULTS" ADD CONSTRAINT "FKKSHFNDYK5DJWRF0Q1PAJFMV2N" FOREIGN KEY ("DISCIPLINE_ID")
	  REFERENCES "SPRING_HIBERNATE"."DISCIPLINE" ("DISCIPLINE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENTEXAMRESULT
--------------------------------------------------------

  ALTER TABLE "SPRING_HIBERNATE"."STUDENTEXAMRESULT" ADD CONSTRAINT "FK98K2RB4MTKYIV1R7BW3FATEXX" FOREIGN KEY ("EXAM_ID")
	  REFERENCES "SPRING_HIBERNATE"."EXAM_RESULTS" ("EXAM_ID") ENABLE;
 
  ALTER TABLE "SPRING_HIBERNATE"."STUDENTEXAMRESULT" ADD CONSTRAINT "FKPOTI46V70YA95HRBVEDWPHO97" FOREIGN KEY ("THESTUDENT_ID")
	  REFERENCES "SPRING_HIBERNATE"."ENGSTUDENT" ("ID") ENABLE;
