CREATE TABLE "HIBERNATE_PRACTICE"."EMPLOYEE" 
   (	"EMPLOYEE_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"HIREDT" TIMESTAMP (6) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"TERMDT" TIMESTAMP (6), 
	 PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
