CREATE TABLE "CREDENTIALS_MANAGER"."CREDENTIALS_MANAGER" 
   (	"ACCOUNT_ID" VARCHAR2(20), 
	"ACCOUNT_NAME" VARCHAR2(200), 
	"ACCOUNT_URL" VARCHAR2(1000), 
	"USER_ID" VARCHAR2(40), 
	"ACCOUNT_PASSWORD" VARCHAR2(40), 
	"PASSWORD_TYPE" VARCHAR2(20), 
	 PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
