CREATE USER LIBRARY_MANAGEMENT IDENTIFIED BY Iofdtiger#16;

GRANT dba TO library_management;

CREATE USER JPA_TRAINING IDENTIFIED BY Iofdtiger#16;

GRANT dba TO JPA_TRAINING;

CREATE USER SPRING_HIBERNATE_MVC IDENTIFIED BY Iofdtiger#16;

GRANT dba TO SPRING_HIBERNATE_MVC;

CREATE USER SPRING_TRAINING IDENTIFIED BY Iofdtiger#16;

GRANT dba TO SPRING_TRAINING;

CREATE USER SPRING_HIBERNATE IDENTIFIED BY Iofdtiger#16;

GRANT dba TO SPRING_HIBERNATE;

